"$schema" = "node_modules/wrangler/config-schema.json"
main = "./.output/server/index.mjs"
compatibility_date = "2026-03-01"

[assets]
binding = "ASSETS"
directory = "./.output/public/"

[observability]
enabled = true

[[r2_buckets]]
binding = "R2"

[[d1_databases]]
binding = "DB"
migrations_table = "_hub_migrations"
migrations_dir = "./.output/server/db/migrations/sqlite/"

[[kv_namespaces]]
binding = "KV"

[[kv_namespaces]]
binding = "CACHE"